// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvlmisccurgstpdjfcmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2bG1pc2NjdXJnc3RwZGpmY21jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTM3MTcsImV4cCI6MjA2MzM4OTcxN30.8WW4VmYPNmO7ypiEIShC30d9-NfEJt96NFCUGgZbmgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});